stages:
  - build
  - test
  - clean
build_all:
  stage: build
  script: 
    - ./.build_all.sh 
test_all:
  stage: test
  script: 
    - ./.test_all.sh
cleanup:
  stage: clean
  script: 
    - ./.clean_all.sh
  when: always
